import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "@/src/lib/react-query-provider"
import { Toaster } from "react-hot-toast"
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) 
{
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body>
        <div>Headerrr</div>
        <ReactQueryProvider>
          {children}
          <Toaster position="top-right" />
        </ReactQueryProvider>
        <div>Foootteeerrr</div>
      </body>
    </html>
  );
}
