import type { Metadata } from "next";
import "@/src/app/globals.css";
import Navbar from "@/src/components/navbar-user"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({ children }: Readonly<{children: React.ReactNode;}>) 
{
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
